name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 */12 * * *' # Runs cada 12 horas
  workflow_dispatch: # Run workflow manually

permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Pull in blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: |
            https://achalmaedison.netlify.app/blog/index.xml
          max_post_count: 10
          retry_count: 3
          retry_wait_time: 5
          disable_item_validation: false
          commit_message: "üìù Actualizado con las √∫ltimas publicaciones del blog"
          committer_username: "blog-post-bot"
          committer_email: "blog-post-bot@example.com"
